#!/bin/sh
#
#
echo '#'
echo '# Creation d un tunnel ssh entre la machine perso et une machine du boulot'
echo '#'
echo '# Ce tunnel se fait en trois parties'
echo '#  - à partir de VLR6180X, on creuse le tiers central du tunnel avec l option -R de ssh'
echo '#  - à partir de la machine perso, on creuse le premier tiers du tunnel avec l option -L'
echo '#  - si besoin, apres avoir réveiller VLR6180Y à partit de VLR6180X, on creuse le 3ème tiers du tunnel entre les deux machines du bureau'
echo '#'
echo '#   Machine Perso           Relais                   Boulot 1                Boulot 2'
echo '#'
echo '#                            DS214                                                   '
echo '#                 3_2                     3_1'
echo '#       Tux0                                         VLR6180X     3_3        VLR6180Y'
echo '#                 3_2                     3_1'
echo '#                        mail.cdalr.fr                                               '
echo '#'
echo '#'
echo '#'
echo '# Mosh, est une alternative à ssh'
echo '# https://fr.wikipedia.org/wiki/Mosh_%28logiciel%29'
echo '# https://mosh.mit.edu/'
echo '# '
echo '# Mosh a des avantages et des inconvénients'
echo '#  - Avantages'
echo '#     - Replaces interactive SSH. Instant keystroke response, robust to roaming.'
echo '#  - Inconvénients'
echo '#     - But you ll need working UDP.'
echo '#     - No X forwarding : -A : SSH Agent Forwarding n est pas encore supporté'
echo '#     - No X forwarding : -X : X forward n est pas encore supporté'
echo '# '
echo '# Il faudra donc créer un tunnel pour faire passer les connexions udp'
echo '# car elles aussi, elles semblent bloquer par le firewall'
echo '# Cela est possible en suivant ces explications'
echo '#   http://zarb.org/~gc/html/udp-in-ssh-tunneling.html'
echo '#   http://superuser.com/questions/53103/udp-traffic-through-ssh-tunnel'

echo '#'
echo '#'
echo '# Un autre utilitaire à étudier : xpra'
echo '#'
echo '#  http://www.xpra.org/'
echo '#    To start an application (a simple xterm in this example) on a remote system and display it your local machine, simply run: #  '
echo '#  '
echo '#      xpra start ssh:SERVERHOSTNAME:100 --start-child=xterm'
echo '#  '
echo '#    This is similar to ssh -X, except it is faster and you can disconnect and re-connect to the session as many times as you like. (obviously xpra must be installed on your server host) '
echo '#    To re-connect or to connect to this session from another machine, use the attach command (you can also use the xpra_launcher GUI):'
echo '#  '
echo '#      xpra attach ssh:serverhostname:100'
echo '#  '
echo '#    You can find many more usage examples here.'
echo '#  '
echo '# http://www.xpra.org/trac/wiki/Usage'
