#!/bin/sh



# 8ème Partie - Installation d'un environnement OSM
###############################################
# Installation d'un environnement OSM
echo "# 8ème Partie - Installation de mapnik, tirex, tileman"
echo "######################################################"
echo "#"
echo "# Ce script présente l'installation de tirex et tileman"
echo "#"
echo "# Attention, il faut d'abord installer mapnik !"
echo "# installOSMMapnik.sh"
echo "#"
echo "# Avant d'installer tirex et tileman, il faut en effet que mapnik soit"
echo "# présent."
echo "# Après installation de mapnik, il faut "
echo "# redémarrer un nouveau shell, de facon a ce que mapnik-config soit connu"
echo "# pour enfin installer tirex et tilman"
echo "#"
echo "# Installation de tileman "
echo "#"
echo "# https://github.com/osmfj/tileman/blob/master/INSTALL.md"
echo "#"
echo "cd .."
      cd ..
echo "pwd"
      pwd
echo "rm -rf tileman"
      rm -rf tileman
echo "git clone https://github.com/osmfj/tileman.git"
      git clone https://github.com/osmfj/tileman.git
echo "cd tileman"
      cd tileman
echo "git submodule init"
      git submodule init
echo "git submodule update"
      git submodule update
echo "#"
echo "# Ensuite, pour installer nginx-extras"
echo "# il faut ajouter un dépot PPA"
echo "# Sur Ubuntu, c'est ok, cf installOSMTilemanUbuntu.sh"
echo "# mais pour Debian,"
echo "# on peut suivre la procédure indiquée ici :"
echo "# https://wiki.debian.org/CreatePackageFromPPA"
echo "# step 1, sur la page"
echo "#   https://launchpad.net/~osmjapan/+archive/ubuntu/ppa"
echo "#   recuperation de l'url"
echo "#   deb-src http://ppa.launchpad.net/osmjapan/ppa/ubuntu YOUR_UBUNTU_VERSION_HERE main "
echo "# step 2, sur cette même page,"
echo "#   on remarque que la derniere version publiée est"
echo "#   trusty"
echo "# step 3, la ligne pour le sources.list est donc"
echo "#   deb-src http://ppa.launchpad.net/osmjapan/ppa/ubuntu trusty main "
echo "# step 4, le dépot peut etre ajoute à la main ou via synaptic"
echo "# step 5, sur la page, on a aussi l'info"
echo "#   Signing key:"
echo "#     1024R/CE5BFF82 (What is this?)"
echo "#   Fingerprint:"
echo "#     F32C5C884411317A82488233F42FF838CE5BFF82"
echo "#   la commande pour ajouter la cle est donc"
echo "# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE5BFF82"
echo "#"
echo "# sudo aptitude update"
echo "# sudo aptitude install nginx-extras"
echo "#"
echo "# sudo aptitude install geoip-database"
echo "# sudo aptitude install lua-bitop"
echo "# sudo aptitude install lua5.1"
echo "#"
echo "# sudo apt-get install devscripts build-essential"
echo "# sudo apt-get install dh-lua libcgal-dev cmake"
echo "# sudo apt-get source --build lua-nginx-osm"
echo "# sudo dpkg -i lua-nginx-osm_0.44ubuntu1_all.deb"
echo "#"
echo "# sudo apt-get source --build tirex"
echo "# sudo aptitude install libipc-sharelite-perl"
echo "# sudo aptitude install libmapnik-dev"
echo "# sudo aptitude install libsigc++-2.0-dev"
echo "# sudo dpkg -i tirex-core_0.4.2tileman2_amd64.deb"
echo "#"
echo "# Attention, pour le paquet tileman, il y a une modif à faire à la main"
echo "# sudo apt-get source --build tileman"
echo "# sudo aptitude install osm2pgsql"
echo "# sudo dpkg -i tileman_1.4.1_all.deb"
echo "# et hooo, déception, ca ne fonctionne pas..."
echo "# Attention : modif du fichier debian/control pour la gestion des dependances"
echo "# sudo vi tileman-1.4.1/debian/control"
echo "# afin de changer les paquets "
echo "# postgresql-9.3-postgis-2.1 en postgresql-9.4-postgis-2.1"
echo "# postgresql-9.3-postgis-scripts en postgresql-9.4-postgis-scripts"
echo "#"
echo "# on recommence le build"
echo "# sudo apt-get source --build tileman"
echo "# et on test l'install"
echo "# sudo dpkg -i tileman_1.4.1_all.deb"
echo "# et yes, ca fonctionne !"
echo "#"
echo "# sudo ln -s /etc/nginx/sites-available/tileman-proxy /etc/nginx/sites-enabled/tileman-proxy"
echo "# sudo ln -s /etc/nginx/sites-available/tileman-server /etc/nginx/sites-enabled/tileman-server"
echo "#"
echo "# sudo service nginx stop"
echo "# sudo systemctl status nginx.service"
echo "# sudo mkdir -p /opt/tileman/cache"
echo "# sudo service nginx start"
echo "#"
echo "#---------------------------------------------"
echo "# Utilisation conjointe de tirex et tileman"
echo "#"
echo "# http://wiki.openstreetmap.org/wiki/Tirex/Quick_Start"
echo "# https://github.com/osmfj/tileman/blob/master/INSTALL.md"
echo "#"
echo "# Visualisation des logs"
echo "#   Vérification que tirex fonctionne"
echo "#     tirex-status --once --extended"
echo "#     tail -f /var/log/syslog"
echo "#     tail -f /var/log/tirex/jobs.log"
echo "#   Vérification que nginx fonctionne"
echo "#     tail -f /var/log/nginx/access.log"
echo "#     tail -f /var/log/nginx/error.log"
echo "#     firefox http://localhost"
echo "#     firefox http://tile"
echo "#     firefox http://static"
echo "#"
echo "# Visualisation des paramètres"
echo "#   nginx"
echo "#     vi /etc/nginx/sites-enabled/tileman-proxy"
echo "#   tirex"
echo "#       tirex-check-config"
echo "#       tirex-tiledir-check test"
echo "#       tirex-tiledir-check example"
echo "#       vi /etc/tirex/tirex.conf"
echo "#     Les maps de tirex"
echo "#         en bas de la commande tirex-status --extended"
echo "#       test"
echo "#       example"
echo "#         vi /usr/share/tirex/example-map/example.xml"
echo "#     Les renderers de tirex"
echo "#         au milieu de la commande tirex-status --extended"
echo "#         ls -al /etc/tirex/renderer/"
echo "#       test"
echo "#         vi /etc/tirex/renderer/test.conf"
echo "#         vi /etc/tirex/renderer/test/checkerboard.conf"
echo "#"
echo "# Lancement des serveurs"
echo "#   Service nginx"
echo "#     Configuration du nom de la machine, cf param de nginx"
echo "#       sudo vi /etc/hosts"
echo "#     sudo service nginx status"
echo "#     sudo service nginx stop"
echo "#     sudo systemctl status nginx.service"
echo "#     sudo mkdir -p /opt/tileman/cache"
echo "#     sudo service nginx start"
echo "#     sudo service nginx start"
echo "#   Service tirex"
echo "#     sudo service tirex-master status"
echo "#     sudo service tirex-backend-manager status"
echo "#"
echo "# Fabrication des tuiles, sollicitation par batch"
echo "#   Sollicitation de la fabrication des tuiles par batch"
echo "#     ls -al /var/lib/tirex/tiles/test"
echo "#     tirex-batch --prio=1 map=test z=0 x=0 y=0"
echo "#     ls -al /var/lib/tirex/tiles/test/0/0/0/0/0/0.meta"
echo "#   Sollicitation de la fabrication des tuiles par batch"
echo "#     ls -al /var/lib/tirex/tiles/example"
echo "#     tirex-batch --prio=1 map=example z=0 x=0 y=0"
echo "#     ls -al /var/lib/tirex/example/test/0/0/0/0/0/0.meta"
echo "#   Sollicitation de la fabrication des tuiles par web, direct"
echo "#     firefox http://tile/0/0/0.png"
echo "#     firefox http://tile/4/7/5.png"
echo "#     firefox http://tile/5/15/11.png"
echo "#     firefox http://tile/6/31/22.png"
echo "#     firefox http://tile/7/63/45.png"
echo "#     firefox http://tile/8/127/90.png"
echo "#     firefox http://tile/9/254/181.png"
echo "#     firefox http://tile/10/508/363.png"
echo "#     firefox http://tile/11/1017/727.png"
echo "#     firefox http://openlayers.org/en/v3.15.1/examples/canvas-tiles.html"
echo "#     firefox http://tile/12/2034/1454.png"
echo "#   Sollicitation de la fabrication des tuiles par web, via OpenLayers"
echo "#     http://openlayers.org/en/v3.15.1/examples/"
echo "#   Sollicitation de la fabrication des tuiles par qgis"
echo "#     qgis avec extension openstreetmap et tilelayer plugin"
echo "#     http://www.3liz.com/blog/rldhont/index.php?post/2012/07/17/Les-Tuiles-OpenStreetMap-dans-QGIS"
echo "#     http://www.portailsig.org/content/qgis-visualiser-les-tuiles-tms-openstreetmap-et-autres-avec-gdal-ou-les-extensions-tilelayer"
echo "#"
echo "#"
echo "#---------------------------------------------"


echo "#"
echo "#"
echo "#"

echo "cd ../environnementTravail"
      cd ../environnementTravail
echo "pwd"
      pwd


echo "#"
