--
-- Creation des schemas pour la base origine
--

-- 17
CREATE SCHEMA IF NOT EXISTS "CDA__Etape_01" AUTHORIZATION "CDA";
CREATE SCHEMA IF NOT EXISTS "CDA__Etape_02" AUTHORIZATION "CDA";
CREATE SCHEMA IF NOT EXISTS "CDA__Etape_03" AUTHORIZATION "CDA";
CREATE SCHEMA IF NOT EXISTS "CDA__Etape_04" AUTHORIZATION "CDA";
CREATE SCHEMA IF NOT EXISTS "CDA__Etape_05" AUTHORIZATION "CDA";
CREATE SCHEMA IF NOT EXISTS "Departement__Etape_01" AUTHORIZATION "Departement";
CREATE SCHEMA IF NOT EXISTS "Departement__Etape_02" AUTHORIZATION "Departement";
CREATE SCHEMA IF NOT EXISTS "Departement__Etape_03" AUTHORIZATION "Departement";
CREATE SCHEMA IF NOT EXISTS "Departement__Etape_04" AUTHORIZATION "Departement";
CREATE SCHEMA IF NOT EXISTS "Departement__Etape_05" AUTHORIZATION "Departement";
CREATE SCHEMA IF NOT EXISTS "DGFiP__Etape_01" AUTHORIZATION "DGFiP";
CREATE SCHEMA IF NOT EXISTS "DGFiP__Etape_02" AUTHORIZATION "DGFiP";
CREATE SCHEMA IF NOT EXISTS "DGFiP__Etape_03" AUTHORIZATION "DGFiP";
CREATE SCHEMA IF NOT EXISTS "DGFiP__Etape_04" AUTHORIZATION "DGFiP";
CREATE SCHEMA IF NOT EXISTS "DGFiP__Etape_05" AUTHORIZATION "DGFiP";
CREATE SCHEMA IF NOT EXISTS "ERDF__Etape_01" AUTHORIZATION "ERDF";
CREATE SCHEMA IF NOT EXISTS "ERDF__Etape_02" AUTHORIZATION "ERDF";
CREATE SCHEMA IF NOT EXISTS "ERDF__Etape_03" AUTHORIZATION "ERDF";
CREATE SCHEMA IF NOT EXISTS "ERDF__Etape_04" AUTHORIZATION "ERDF";
CREATE SCHEMA IF NOT EXISTS "ERDF__Etape_05" AUTHORIZATION "ERDF";
CREATE SCHEMA IF NOT EXISTS "SDE__Etape_01" AUTHORIZATION "SDE";
CREATE SCHEMA IF NOT EXISTS "SDE__Etape_02" AUTHORIZATION "SDE";
CREATE SCHEMA IF NOT EXISTS "SDE__Etape_03" AUTHORIZATION "SDE";
CREATE SCHEMA IF NOT EXISTS "SDE__Etape_04" AUTHORIZATION "SDE";
CREATE SCHEMA IF NOT EXISTS "SDE__Etape_05" AUTHORIZATION "SDE";
CREATE SCHEMA IF NOT EXISTS "SDEER__Etape_01" AUTHORIZATION "SDEER";
CREATE SCHEMA IF NOT EXISTS "SDEER__Etape_02" AUTHORIZATION "SDEER";
CREATE SCHEMA IF NOT EXISTS "SDEER__Etape_03" AUTHORIZATION "SDEER";
CREATE SCHEMA IF NOT EXISTS "SDEER__Etape_04" AUTHORIZATION "SDEER";
CREATE SCHEMA IF NOT EXISTS "SDEER__Etape_05" AUTHORIZATION "SDEER";
CREATE SCHEMA IF NOT EXISTS "Soluris__Etape_01" AUTHORIZATION "Soluris";
CREATE SCHEMA IF NOT EXISTS "Soluris__Etape_02" AUTHORIZATION "Soluris";
CREATE SCHEMA IF NOT EXISTS "Soluris__Etape_03" AUTHORIZATION "Soluris";
CREATE SCHEMA IF NOT EXISTS "Soluris__Etape_04" AUTHORIZATION "Soluris";
CREATE SCHEMA IF NOT EXISTS "Soluris__Etape_05" AUTHORIZATION "Soluris";
CREATE SCHEMA IF NOT EXISTS "VLR__Etape_01" AUTHORIZATION "VLR";
CREATE SCHEMA IF NOT EXISTS "VLR__Etape_02" AUTHORIZATION "VLR";
CREATE SCHEMA IF NOT EXISTS "VLR__Etape_03" AUTHORIZATION "VLR";
CREATE SCHEMA IF NOT EXISTS "VLR__Etape_04" AUTHORIZATION "VLR";
CREATE SCHEMA IF NOT EXISTS "VLR__Etape_05" AUTHORIZATION "VLR";

show search_path;
