#!/bin/sh

echo "#"
echo "# Installation de GeoSHAPE"
echo "#"
echo "#"
echo "# https://github.com/ROGUE-JCTD/rogue_geonode "
echo "#"
echo "# installation de vagrant"
echo "#"
echo "sudo aptitude install vagrant"
      sudo aptitude install vagrant
echo "#"
echo "#"
echo "#"
echo "git clone https://github.com/ROGUE-JCTD/rogue-chef-repo.git"
      git clone https://github.com/ROGUE-JCTD/rogue-chef-repo.git
echo "cd rogue-chef-repo"
      cd rogue-chef-repo
echo "vagrant up"
      vagrant up
echo "#"
echo "#"
echo "# Les commandes a connaitre sont"
echo "#"
echo "# Liste des machines vagrant en cours"
echo "#"
echo "# vagrant global-status"
echo "#"
echo "# Se connecter à la machine dont l id est a761715"
echo "#"
echo "# vagrant ssh a761715"
echo "#"
echo "# Ensuite, il faut suivre la doc qui est ici :"
echo "# https://docs.google.com/document/d/1KMpk6dXuqvwfEi0pfRpaGY62j6ikoYtpYUPU0sJQAmk/edit#heading=h.hkbyul6u8lkg"
echo "#"
echo "# sudo su -"
echo "# apt-get install git"
echo "# cd /opt"
echo "# git clone https://github.com/ROGUE-JCTD/rogue-chef-repo.git"
echo "# bash rogue-chef-repo/scripts/geoshape-install.sh"

