#!/bin/sh



# 8ème Partie - Installation d'un environnement OSM
###############################################
# Installation d'un environnement OSM
echo "# 8ème Partie - Installation d'un environnement OSM"
echo "###############################################"
echo "#"
echo "# Nous allons créer un environnement "
echo "# (Ici, il faut comprendre le mot environnement comme ensemble d'outils, "
echo "# et non pas comme une environnement virtuel python)"
echo "# pour faciliter la manipulation de données OSM."
echo "#"
echo "# La documentation sur l'installation et l'utilisation de cet"
echo "# environnement est détaillé dans"
echo "# Linux Magazine N°188"
echo "#"
echo "# Pré-requis avant d'installer les données OSM"
echo "# Des outils comme osmosis sont développés en Java"
echo "# D'autre part, il faut aussi veillez  avoir postgresql qui tourne..."
echo "#"
echo "# La base de données postgresql, avec l'extension postgis, nécessaire pour stocker les données"
echo "# L'outil osmosis, nécessaire pour télécharger les données OpenStreetMap, est fourni par le paquet osmosis"
echo "# L'outil osm2pgsql, nécessaire pour importer les données dans postgresql, est fourni par le paquet osm2pgsql"
echo "# L'outil mapnik est installe manuellement"
echo "# L'outil tirex, equivalent de renderd, nécessaire pour fabriquer les tuiles, est installé manuellement"
echo "# Un script lua couplé au serveur NGINX, c'est l'outil tileman, remplace le module apache mod_tile."
echo "# Cette partie de configuaration est nécessaire pour servir les tuiles"
echo "# Cette partie est aussi installé manuellement"
echo "#"
echo "# La liste des composants d'OSM est ici"
echo "# http://wiki.openstreetmap.org/wiki/FR:Component_overview"
echo "#"
echo "# Mapnik est l'outil principal pour le rendu"
echo "# http://wiki.openstreetmap.org/wiki/FR:Rendu"
echo "# http://wiki.openstreetmap.org/wiki/FR:Mapnik"
echo "# "
echo "# Tirex"
echo "# http://wiki.openstreetmap.org/wiki/Tirex"
echo "#"
echo "# Tileman"
echo "# https://github.com/osmfj/tileman"
echo "# http://osmfj.github.io/tileman/"
echo "# http://miurahr.github.io/slides/2013-0908-tileman.html#/title"
echo "#"
echo "# Ces paquets sont donc :"
echo "#"
echo "sudo aptitude install -y osmosis"
      sudo aptitude install -y osmosis
echo "sudo apt-get install -y osmosis"
      sudo apt-get install -y osmosis
echo "sudo aptitude install -y osm2pgsql"
      sudo aptitude install -y osm2pgsql
echo "sudo apt-get install -y osm2pgsql"
      sudo apt-get install -y osm2pgsql
echo "#"
echo "# pour memoire..."
echo "# sudo apt-get install libapache2-mod-tile"
      #sudo apt-get install libapache2-mod-tile
echo "#"
echo "# Le paquet gis-osm regroupe les utilitaires pour la manipulation des données osm"
echo "#"
echo "# L'installation de ce paquet necessite une interaction"
echo "#"
echo "# Configuration de openstreetmap-carto"
echo "# Des données complémentaires doivent etre chargées dans le repertoire"
echo "# /usr/share/openstreetmap-carto/"
echo "# à l'aide du script"
echo "# get-shapefiles.sh"
echo "#"
echo "# Configuration de openstreetmap-carto"
echo "# The stylesheet describes how to render OpenStreetMap data"
echo "# contained within a postgresql database."
echo "# The name of the database is by default debian-osm-carto."
echo "# Name of the postgresql database :"
echo "#"
echo "#"
#echo "sudo aptitude install -y gis-osm nik4 viking"
#      sudo aptitude install -y gis-osm nik4 viking
#echo "sudo aptitude install -y gis-osm"
#      sudo aptitude install -y gis-osm
#echo "sudo aptitude install -y nik4"
#      sudo aptitude install -y nik4
#echo "sudo aptitude install -y viking"
#      sudo aptitude install -y viking
echo "#"
echo "#----------------------"
echo "# Reste a faire :"
echo "#----------------------"
#echo "# ./installOSM.sh"
echo "# ./installOSMCartoCSS.sh"
####echo "# ./installOSMBoostDebian.sh"
echo "# ./installOSMMapnikUbuntuSource.sh"
#echo "# ./installOSMMapnikUbuntuPaquet.sh"
####echo "# ./installOSMPythonMapnikDebian"
echo "# ./installOSMPythonMapnikUbuntu"
echo "# ./installOSMTirex.sh"
####echo "# ./installOSMTilemanDebian.sh"
echo "# ./installOSMTilemanUbuntu.sh"
echo "#----------------------"
echo "#"
echo "# Autres logiciels à étudier :"
echo "#"
echo "# komstik tilelite tilestache opentileserver.org merkaartor osmarender switch2osm/creatingYourOwnTiles Kartograph"
echo "#"
echo "# Avec cette suite d'outils, nous allons maintenant créer quelques petits scripts"
echo "# qui vont automatiser certaines taches :"
echo "#"
echo "# osmCreateRepository.sh"
echo "# osmDownloadFirstTime.sh"
echo "# osmDownloadOtherTime.sh"
echo "# osmImportFirstTime.sh"
echo "# osmImportOtherTime.sh"
echo "# osmRender.sh"

echo "#"
