#!/bin/sh



# 8ème Partie - Installation d'un environnement OSM
###############################################
# Installation d'un environnement OSM
echo "# 8ème Partie - Installation de mapnik, tilestache"
echo "######################################################"
echo "#"
echo "# Ce script présente l'installation de tirex"
echo "#"
echo "# Attention, il faut d'abord installer mapnik et python-mapnik"
echo "# ./installOSMMapnik.sh"
echo "# ./installOSMPythonMapnik.sh"
echo "#"
echo "#"
echo "# Avant d'installer tilestache il faut en effet que mapnik soit présent."
echo "# Après installation de mapnik, il faut "
echo "# redemarrer un nouveau shell, de facon a ce que mapnik-config soit connu"
echo "# pour enfin installer tirex et tilman"
echo "#"
echo "# Installation de tilestache "
echo "#"
echo "# http://tilestache.org/"
echo "# https://hub.docker.com/r/aldoridhoni/mapnik-tilestache/"
echo "# http://mike.teczno.com/notes/tilestache.html"
echo "#"
#echo "export OLDPWDFG=$(pwd)"
#      export OLDPWDFG=$(pwd)
#      echo $OLDPWDFG
#echo "cd .."
#      cd ..
#echo "pwd"
#      pwd
echo "sudo aptitude install -y tilestache"
      sudo aptitude install -y tilestache
echo "sudo apt-get install -y tilestache"
      sudo apt-get install -y tilestache
echo "#"
echo "#"
echo "#"
#echo "sudo aptitude install libtest-simple-perl"
#      sudo aptitude install libtest-simple-perl
#echo "sudo aptitude install libtest-harness-perl"
#      sudo aptitude install libtest-harness-perl
#echo "cd $OLDPWDFG"
#      cd $OLDPWDFG
#echo "pwd"
#      pwd
echo "#"
#echo "#------------------------"
#echo "# Test du fihcier example"
#echo "#------------------------"
#echo "# mapnik-render testMapnik.xml testMapnik.png"
#echo "# mapnik-render /usr/share/tirex/example-map/example.xml testMapnikTirex.png"
echo "#"
echo "#----------------------"
echo "# Utilisation de tilestache "
echo "#----------------------"
echo "# La doc est ici"
echo "# http://wiki.openstreetmap.org/wiki/Tirex/Quick_Start"
echo "#"
#echo "# tirex-status --once --extended"
#echo "# tail -f /var/log/syslog"
#echo "# tail -f /var/log/tirex/jobs.log"
#echo "# ls -al /var/lib/tirex/tiles/test"
#echo "# tirex-batch --prio=1 map=test z=0 x=0 y=0"
#echo "# ls -al /var/lib/tirex/tiles/test/0/0/0/0/0/0.meta"
echo "#----------------------"
echo "#"
echo "# En examinant les logs : "
echo "# tail -f /var/log/syslog"
echo "# on se rend compte que mapnik-render a un problème..."
echo "# Test de mapnik-render"
echo "#  - si mapnik-render a ete installé à partir des sources de mapnik (3.0.12):"
echo "#    /usr/local/bin/mapnik-render testMapnik.xml testMapnik.png"
echo "#  - si mapnik-render a ete installé à partir du paquet mapnik-utils (3.0.9)"
echo "#    /usr/bin/mapnik-render testMapnik.xml testMapnik.png"
echo "#"
echo "# Si on obtient l'erreur comme quoi le plugin shape est absent"
echo "#   Error Could not create datasource for type: 'shape'"
echo "#   (no datasource plugin directories have been successfully registered)"
echo "# alors, il faut, selon cette page"
echo "#   https://github.com/mapnik/mapnik/wiki/PluginArchitecture"
echo "#   https://github.com/mapnik/mapnik/wiki/ShapeFile"
echo "# ... recompiler mapnik avec les bons paramètres (???)"
echo "#"
echo "# Avant de recompiler, un nouveau test :"
echo "#   ls -al /usr/local/lib/mapnik/input"
echo "#"
echo "#----------------------"
echo "# Reste a faire :"
echo "#----------------------"
#echo "# ./installOSM.sh"
#echo "# ./installOSMCartoCSS.sh"
####echo "# ./installOSMBoostDebian.sh"
#echo "# ./installOSMMapnikDebianPaquet.sh"
####echo "# ./installOSMMapnikUbuntuSource.sh"
##echo "# ./installOSMMapnikUbuntuPaquet.sh"
#echo "# ./installOSMPythonMapnikDebian.sh"
##echo "# ./installOSMPythonMapnikUbuntu.sh"
#echo "# ./installOSMTirex.sh"
#echo "# ./installOSMTilemanDebian.sh"
##echo "# ./installOSMTilemanUbuntu.sh"
echo "#----------------------"


echo "#"
