#!/bin/sh



# 8ème Partie - Installation d'un environnement OSM
###############################################
# Installation d'un environnement OSM
echo "# 8ème Partie - Installation de python-mapnik"
echo "######################################################"
echo "#"
echo "# Ce script présente l'installation de python-mapnik"
echo "#"
echo "# Il semble que le lien entre python et mapnik"
echo "# n'est pas automatique. "
echo "#"
echo "# En effet, après avoir installé mapnik, il n'est pas "
echo "# possible de faire un import python : le module n'est pas connu"
echo "#"
echo "# Il s'agit donc d'installer python-mapnik en plus de mapnik"
echo "#"
echo "# En effet, d'après la page"
echo "# https://github.com/mapnik/mapnik/blob/master/INSTALL.md"
echo "#"
echo "#   'Python bindings are not included by default.''"
echo "#   'You'll need to add those separately.'"
echo "#   'Build from source: https://github.com/mapnik/python-mapnik'"
echo "#"
echo "#"
echo "# Installation de python3-mapnik à partir du paquet debian"
echo "#"
echo "# plus d'infos sur https://github.com/mapnik/python-mapnik"
echo "#"
echo "# Installation de python3-mapnik"
echo "sudo apt-get -y install python3-mapnik"
      sudo apt-get -y install python3-mapnik
echo "#"
echo "# Installation de python-mapnik"
echo "#"
echo "# Attention : Installation de python-mapnik ..... : c'est necessaire pour mapnik-render"
#echo "sudo aptitude install python-mapnik"
#      sudo aptitude install python-mapnik
#echo "sudo aptitude remove python-mapnik"
#      sudo aptitude remove python-mapnik
echo "sudo apt-get -y install python-mapnik"
      sudo apt-get -y install python-mapnik

echo "#"
echo "# Installation de nik2img (python2) et nik4 (python3)"
echo "sudo -H pip3 install nik4"
      sudo -H pip3 install nik4
echo "sudo -H pip install nik2img"
      sudo -H pip install nik2img

echo "#"
echo "#----------------------"
echo "# Test de l'installation de python-mapnik :"
echo "#----------------------"
echo "# La doc est ici"
echo "# https://github.com/mapnik/mapnik/wiki/GettingStartedInPython"
echo "#"
echo "# Test 1 : python"
echo '    python -c "import sys; print('\'\\\\n\''.join(sys.path))"'
echo "# Test 2 : python import mapnik"
echo '    python -c "import mapnik;print(mapnik.__file__)" # should return the path to the python bindings and no errors'
echo '    python -c "from mapnik import DatasourceCache as c; print('"'shape'"' in c.plugin_names())"'
echo '    python -c "from mapnik import DatasourceCache as c; print('\'\\\\n\''.join(c.plugin_names()))"'
echo "# Test 3 : python et script maison"
echo "    python testMapnik.py"
echo '# Test 4 : rendu avec des outils python (nik2img et nik4)'
echo "#   nik2img et nik4 : sont deux utilitaires qui utilisent mapnik,"
echo "#   en passant par python :  il faut donc installer python-mapnik"
echo "#   avant de pouvoir utiliser ces deux outils"
echo "#   https://github.com/springmeyer/nik2img/blob/master/INSTALL.txt"
echo "#   https://github.com/Zverik/Nik4"
echo "    sudo -H pip3 install nik4"
echo "    sudo -H pip install nik2img"
echo "#   Après installation, nous pouvons utiliser un autre test interne de mapnik"
echo "    cd ../mapnik ; \\"
echo "    make rendu ;\\"
echo "    cd ../environnementTravail ; \\"
echo "    display ...."
echo '# Test 5 : Test de mapnik avec les données osm (et configuration xml)'
echo "#   http://wiki.openstreetmap.org/wiki/User:Stanton/Mapnik_Test_Server"
echo "#   Un outil permet de generer un fichier xml"
echo "#   (fichier qui contient les paramètres pour que mapnik genère une carte)"
echo "#   à partir informations sources (base postgresql qui contient les données osm)"
echo "#   http://wiki.openstreetmap.org/wiki/User:Stanton/Mapnik_Test_Server#Mapnik_Initialization"
echo "#----------------------"
echo '#'
echo "#----------------------"
echo "# Test de l'installation de python-mapnik et d'openstreetmap-carto-vector-tiles"
echo "#----------------------"
echo "# Nous avons précedemment installé cartocss"
echo "#"
echo "# Nous allons tester son utilisation dans son deuxième mode,"
echo "# c'est à dire, l'utilisation des fichier (.mss) en tant que parammètres pour mapnik"
echo "#"
echo "# La doc est ici"
echo "# https://github.com/geofabrik/openstreetmap-carto-vector-tiles/blob/master/INSTALL.md"
echo "#"
echo "# Test 6 : Test de mapnik avec les données osm (et configuration cartocss)"
echo "#   https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md"
echo "#   Jusqu'à présent, pour configurer le rendu,"
echo "#   - nous avions utilisé un fichier xml,"
echo "#   - nous allons maintenant utiliser un fichier css"
echo "#"
echo "#   Jusqu'à présent donc, avec mapnik, il fallait avoir un fichier xml pour decrire le rendu"
echo "#   Pour les données d'OpenStreetMap, il fallait donc :"
echo "#     1. generer un fichier xml avec la commande generate-xml.py"
echo "#     2. lancer le rendu avec la commande mapnik-render"
echo "# "
echo "#   Dorénavant, avec cartocss, il faut avoir un fichier de type css"
echo "#   la syntaxe est plus souple et plus lisible"
echo "#   L'edition peut-etre faite à la main ou avec des outils (mapbox ?)"
echo "#   Pour rendre les données d'OpenStreetMap, il faut dorénavant:"
echo "#     1. adapter le fichier css"
echo "#     2. lancer le rendu"
echo "#----------------------"
echo "#"
echo "#----------------------"
echo "# Reste a faire :"
echo "#----------------------"
#echo "# ./installOSM.sh"
#echo "# ./installOSMCartoCSS.sh"
####echo "# ./installOSMBoostDebian.sh"
#echo "# ./installOSMMapnikDebianPaquet.sh"
#####echo "# ./installOSMMapnikUbuntuSource.sh"
##echo "# ./installOSMMapnikUbuntuPaquet.sh"
#echo "# ./installOSMPythonMapnikDebian.sh"
##echo "# ./installOSMPythonMapnikUbuntu.sh"
echo "# ./installOSMTirex.sh"
echo "# ./installOSMTilemanDebian.sh"
##echo "# ./installOSMTilemanUbuntu.sh"
echo "#----------------------"
echo "#"

echo "#"
