--
-- Creation des schemas pour la base sandbox
--

-- 17
--CREATE SCHEMA IF NOT EXISTS "CDA" AUTHORIZATION "CDA";
--CREATE SCHEMA IF NOT EXISTS "Departement" AUTHORIZATION "Departement";
--CREATE SCHEMA IF NOT EXISTS "DGFiP" AUTHORIZATION "DGFiP";
--CREATE SCHEMA IF NOT EXISTS "erdf" AUTHORIZATION "erdf";
--CREATE SCHEMA IF NOT EXISTS "SDE" AUTHORIZATION "SDE";
--CREATE SCHEMA IF NOT EXISTS "SDEER" AUTHORIZATION "SDEER";
--CREATE SCHEMA IF NOT EXISTS "Soluris" AUTHORIZATION "Soluris";
--CREATE SCHEMA IF NOT EXISTS "VLR" AUTHORIZATION "VLR";

CREATE SCHEMA IF NOT EXISTS "fred__PlanProjet" AUTHORIZATION "fred";
CREATE SCHEMA IF NOT EXISTS "fred__PlanExecution" AUTHORIZATION "fred";
CREATE SCHEMA IF NOT EXISTS "fred__PlanTopoNonControle" AUTHORIZATION "fred";
CREATE SCHEMA IF NOT EXISTS "fred__Controle" AUTHORIZATION "fred";
CREATE SCHEMA IF NOT EXISTS "fred__PlanTopoControle" AUTHORIZATION "fred";

show search_path;

-- 17_VLR
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_Carto AUTHORIZATION Fred;
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_EauPotable;
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_Eclairage;
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_VoirieTravaux;
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_VoiriePluvial;


-- 17_VLR_Carto
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_Carto_Francois AUTHORIZATION Francois;
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_Carto_Fred AUTHORIZATION Fred;
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_Carto_Michel AUTHORIZATION Michel;
--CREATE SCHEMA IF NOT EXISTS PCRS_VLR_Carto_Pascal AUTHORIZATION Pascal;
