language: erlang
#
before_install:
  - "sudo useradd osm"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq python-software-properties"
  - "sudo apt-add-repository -y ppa:osmjapan/ppa"
  - "sudo apt-add-repository -y ppa:lwarx/postgis-pg93-bp"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq nginx-openresty libmapnik-dev ttf-unifont ttf-dejavu ttf-dejavu-core ttf-dejavu-extra"
  - "sudo apt-get install -qq postgresql-9.1 postgresql-contrib-9.1 postgresql-9.1-postgis-2.1"
  - "sudo apt-get install -qq --no-install-recommends osm2pgsql tirex-core tirex-backend-mapnik tirex-example-map"
  - "sudo apt-get install -qq geoip-database lua5.1 lua-bitop openjdk-7-jre lua-nginx-osm"
  - "sudo apt-get install -qq devscripts debhelper dh-autoreconf build-essential git"
  - "sudo apt-get install -qq libfreexl-dev libgdal-dev python-gdal gdal-bin"
  - "sudo apt-get install -qq libxml2-dev python-libxml2 libsvg"
  - "sudo apt-get install -qq libjs-leaflet"
  - "sudo apt-get install -qq openstreetmap-mapnik-stylesheet-data"
  - "sudo osmosis/osmosis-installer.sh"
#
install:
  - "make PREFIX=/usr HTMLDIR=/var/www CONFDIR=/etc CACHEDIR=/var/cache/tileman STATICDIR=/var/lib/tileman/tiles WORKDIR=/var/lib/osmosis install"
#
# command to run tests
script:
  - "make PREFIX=/usr HTMLDIR=/var/www CONFDIR=/etc CACHEDIR=/var/cache/tileman STATICDIR=/var/lib/tileman/tiles WORKDIR=/var/lib/osmosis test_install"
  - "make test_service_start"
  - "make PREFIX=/usr HTMLDIR=/var/www CONFDIR=/etc CACHEDIR=/var/cache/tileman STATICDIR=/var/lib/tileman/tiles WORKDIR=/var/lib/osmosis test"

